vars = 1
resoftest = 2
whatwelearn = 3
whatwelearntest = 4
reg = 0
ressql = 0
reswhatwelearn = 0
resvars = 1
testvariant = 0
opr = {

    'привет' : 'доров',
    'как дела' : 'норм. ты как?',
    'хорошо.' : 'что делаешь?',
    'сижу. ты?' : 'лежу.',
    'тест' : 'тест',
    'учебник' : 'учебник',
    'понял' : 'понял',
    'закончить обучение' : 'закончить обучение',
}
TEST =  {
        "СЛОЖЕНИЕ":{
                "тст" : ("AgACAgIAAxkBAAIYCV-T0keMzLI4AbaYzDqpKq4CuJ6VAAKtrjEbf6GgSP6nLiwp3CdO2WcWmC4AAwEAAwIAA20AA5QoAgABGwQ",
                         "AgACAgIAAxkBAAIYC1-T0lKNFYyg_ZutEul7JA_ZbJD2AAKurjEbf6GgSITcCbnXcr0z3K3rly4AAwEAAwIAA20AA5QsAgABGwQ",
                         "AgACAgIAAxkBAAIYDV-T0lquUKBwy-x93q77X0rmhzA0AAKvrjEbf6GgSNGhgzcCLa-Vu3Roly4AAwEAAwIAA20AA1s6AgABGwQ"),
                "а" : ( "AgACAgIAAxkBAAIgpF-7yfpt5oZQ8UyVLGYr_G9HDMyCAAJ4sDEbx5XZSdFHusgOb0roTE_zly4AAwEAAwIAA20AA8paAwABHgQ",
                        "AgACAgIAAxkBAAIgp1-7yf-pnidZ8Oio7Fzkrhj5UPAcAAJ5sDEbx5XZSXFN58yI92wZKaJMli4AAwEAAwIAA20AA-C-BAABHgQ",
                        "AgACAgIAAxkBAAIgql-7ygKe6KiRn7ylnFwmwMF3_UPhAAJ6sDEbx5XZSUX61RO1s1OnxolGli4AAwEAAwIAA20AA2e5BAABHgQ",
                        "AgACAgIAAxkBAAImCV-83M31uLij-qV8gBDVzA0JlY5HAALRsTEbx5XpSa83mAG2HT2G7RVwly4AAwEAAwIAA20AA_2LAwABHgQ",
                        "AgACAgIAAxkBAAIgsF-7ygjIr0vKvyg41yr9fssdFeHNAAJ7sDEbx5XZSTXe1kJyLMlaqpDlly4AAwEAAwIAA20AAw9rAwABHgQ",
                        "AgACAgIAAxkBAAIgs1-7ygvkO1pGlo5m81zCS3cUgKGHAAJ8sDEbx5XZSR3xrfwPoYtB127Uli4AAwEAAwIAA20AA_EQBAABHgQ"),
                "б" : ( "AgACAgIAAxkBAAIgtl-7yg4obm4GZviyS8XQFzRVxH7vAAJ9sDEbx5XZSTBkuGW9YCLDge8ZlS4AAwEAAwIAA20AA32dBgABHgQ",
                        "AgACAgIAAxkBAAIguV-7yhC1Pu2ZeEG9SB17142a_eqTAAJ-sDEbx5XZSdHsnbXUFjDvP6h0ly4AAwEAAwIAA20AA0h2AwABHgQ",
                        "AgACAgIAAxkBAAIgvF-7yhMEA99HgQ4Mu3y4n0ndgQudAAJ_sDEbx5XZSajXKX1znVme6qRMli4AAwEAAwIAA20AA2LDBAABHgQ",
                        "AgACAgIAAxkBAAIgv1-7yhaCkRahRtrNfhxlxMkmsY8IAAKAsDEbx5XZSdsoKzYdgZyfkPsamC4AAwEAAwIAA20AA2lqAwABHgQ",
                        "AgACAgIAAxkBAAIgwl-7yhlUwRRQi5VVlv1rFYq0xTccAAKBsDEbx5XZSVH1K1CV6A9DWUBSmS4AAwEAAwIAA20AA0A0AQABHgQ",
                        "AgACAgIAAxkBAAIgxV-7yhzRvxOfyAg2u8U-wjGpOvW4AAKCsDEbx5XZSQkFF4ycP28wlQFFli4AAwEAAwIAA20AA-O1BAABHgQ"),
                "в" : ( "AgACAgIAAxkBAAIgyF-7yh6vvqQ-rmSLvZIiqxkJuDLIAAKDsDEbx5XZSQXNqWvH20dYq8QOmC4AAwEAAwIAA20AAyhvAwABHgQ",
                        "AgACAgIAAxkBAAIgy1-7yiGB2eDMSFDLIxDYEFYqW8csAAKEsDEbx5XZSVuoRQKbJZke4kNSmS4AAwEAAwIAA20AAz0zAQABHgQ",
                        "AgACAgIAAxkBAAIgzl-7yiQRL58hBiDRbbhtLkmLeJC-AAKFsDEbx5XZSdoStvGbuFymTZ7oly4AAwEAAwIAA20AA_hsAwABHgQ",
                        "AgACAgIAAxkBAAIg0V-7yidy9GQyiK8un6IU7uR_TmUdAAKGsDEbx5XZSYdH1KcfvktsUs5emi4AAwEAAwIAA20AA240AQABHgQ",
                        "AgACAgIAAxkBAAIg1F-7yiqc9lQNe6OB07mqq7sAAQm-3wACh7AxG8eV2UkF_VAyHd9Ba2Br-5QuAAMBAAMCAANtAANuqQYAAR4E",
                        "AgACAgIAAxkBAAIg11-7yi0fW_uA7ReGvNcoQX6pWbQFAAKIsDEbx5XZSdMU27Vnkiz9aAbZli4AAwEAAwIAA20AA4wLBAABHgQ"),
                "г" : ("AgACAgIAAxkBAAIg2l-7yj7qGx66T5LIm1OIgo87u9W8AAKJsDEbx5XZSbzM_RouKd3ZKEhdmi4AAwEAAwIAA20AAykzAQABHgQ",
                        "AgACAgIAAxkBAAIg3V-7ykG55YQMYrD_8RPz1IEoiG_RAAKKsDEbx5XZSaSlM-F38mwux5pxly4AAwEAAwIAA20AAwt7AwABHgQ",
                        "AgACAgIAAxkBAAIg4F-7ykNNTfTx6MnPndajVGbs-NlIAAKLsDEbx5XZSW91zhY_JNvCaDxHmC4AAwEAAwIAA20AA0NiAwABHgQ",
                        "AgACAgIAAxkBAAIg41-7ykZm6eurSSMgJxBGQqaKwfu3AAKMsDEbx5XZSfJ8zItBi9wHA8YOmC4AAwEAAwIAA20AA9hqAwABHgQ",
                        "AgACAgIAAxkBAAIg5l-7ykn-FEChDpOI6dEUZntO_t-nAAKNsDEbx5XZSUk1iPx02uDmi7vRly4AAwEAAwIAA20AA7dFAwABHgQ",
                        "AgACAgIAAxkBAAIg6V-7yk0Os570XxIl93vNHaaTimFkAAKOsDEbx5XZSdgzum9IsujLMC1EmC4AAwEAAwIAA20AA3RzAwABHgQ")},
        "ДЕЛЕНИЕ" : {
                "а": ("AgACAgIAAxkBAAIel1-6srXpluO5UDFogKq0bKLcdhv0AAKYsTEb16XRSZ8Xtq1W-NycRUpdmi4AAwEAAwIAA20AA0MqAQABHgQ",
                      "AgACAgIAAxkBAAIeml-6sruMsbjfZpppn9-cYaE32NtJAAKZsTEb16XRSYw3VsoWQDCb6y5EmC4AAwEAAwIAA20AA8RoAwABHgQ",
                      "AgACAgIAAxkBAAIenV-6ssGm16uNPQOfUbRS-WKSwPzwAAKasTEb16XRSV_6gCKeMqwszazrly4AAwEAAwIAA20AA9ZgAwABHgQ",
                      "AgACAgIAAxkBAAIeoF-6sslrtxqjSn_nb1kD2c4iQEJoAAKmsTEb16XRScOdJ0EO1zBqrpLlly4AAwEAAwIAA20AAy9jAwABHgQ",
                      "AgACAgIAAxkBAAIeo1-6stTxgk_ilLFl64wzou-OR_MsAAKnsTEb16XRSaXBmFa09Fga7vgamC4AAwEAAwIAA20AA0piAwABHgQ",
                      "AgACAgIAAxkBAAIepl-6suKpDWUN7YS_u7Ifb-qT7BGZAAKosTEb16XRSQIVgQ1avhAYjENSmS4AAwEAAwIAA20AA1csAQABHgQ"),
                "в": ("AgACAgIAAxkBAAIeqV-6svSafczS-VRugXPsxhhBEYjIAAKpsTEb16XRSeyUKvvDrNvHcZxxly4AAwEAAwIAA20AAwV2AwABHgQ",
                      "AgACAgIAAxkBAAIerF-6svmjXqoVUi11WOJK5GKk6Y9iAAKqsTEb16XRSWHaFc28yY2yYkUFly4AAwEAAwIAA20AA3tQAwABHgQ",
                      "AgACAgIAAxkBAAIer1-6sv11Ygccb5n_axJ_3go1qWmZAAKrsTEb16XRSXYkJAktGNAjs3HUli4AAwEAAwIAA20AAysCBAABHgQ",
                      "AgACAgIAAxkBAAIesl-6swKQKEBDTrCqFJEgg576J51XAAKbsTEb16XRSUNqrAvCCLBRZsUOmC4AAwEAAwIAA20AA7JmAwABHgQ",
                      "AgACAgIAAxkBAAIetV-6swZ5BbTPyuu81q-BkianFHH6AAKcsTEb16XRSZmd4j7oYlRkdffVli4AAwEAAwIAA20AA9cOBAABHgQ",
                      "AgACAgIAAxkBAAIeuF-6swsO8sv0FN63r65I9kKCYw-AAAKdsTEb16XRSZpoKRaq8hAZ1N8UmC4AAwEAAwIAA20AA4dgAwABHgQ"),
                "г": ("AgACAgIAAxkBAAIeu1-6sw-O_QRiaF0pgRfMi_GO2S1yAAKesTEb16XRSeQgRIJHUqrvyoFrly4AAwEAAwIAA20AA_9sAwABHgQ",
                      "AgACAgIAAxkBAAIevl-6sxMY60ph90FuWyM9_gLku4vXAAKfsTEb16XRSQABzlnjp7s1Hk7HU5kuAAMBAAMCAANtAAOgKwEAAR4E",
                      "AgACAgIAAxkBAAIewV-6sxgw0ApiFKQHrwqHviLxwlAYAAKgsTEb16XRSVaNynnv4uX3_iKlli4AAwEAAwIAA20AA_REBAABHgQ",
                      "AgACAgIAAxkBAAIexF-6sx3Hnvb4DBm778CvYtn1jJ-BAAKhsTEb16XRSawYEb_G8cwmZaNMli4AAwEAAwIAA20AA-i0BAABHgQ",
                      "AgACAgIAAxkBAAIex1-6syARtVHIJrLVSVhN3aX4X6zOAAKisTEb16XRSb6bv4-WFyB0dPtply4AAwEAAwIAA20AA-Z6AwABHgQ",
                      "AgACAgIAAxkBAAIeyl-6syWmntqf3Hz2BH0RrKOsCMlOAAKjsTEb16XRScuNY_W1Ij5sUfTAly4AAwEAAwIAA20AA7dAAwABHgQ")},
        "УМНОЖЕНИЕ":{
                "а" : ("AgACAgIAAxkBAAIfEl-7o7-KDUJsu6gV3PkRTPR4YRp2AAIlsDEbx5XZSfWYtj0yQ7L_A8rUly4AAwEAAwIAA20AA6JFAwABHgQ",
                        "AgACAgIAAxkBAAIfF1-7o88NLUvJ7HQIgnlhe_dHX2nnAAImsDEbx5XZSbYo2xJPVOzs7HBTmC4AAwEAAwIAA20AA75ZAwABHgQ",
                        "AgACAgIAAxkBAAIfGl-7o9TLfDXh7boOtoYnOSr0jZjiAAInsDEbx5XZSTH-htXMwhwkT8zKmS4AAwEAAwIAA20AAyr9AAIeBA",
                        "AgACAgIAAxkBAAIfHV-7o9msmOTBI49IlHWR10BXb_aVAAIosDEbx5XZSawpvP_HprvatMhTmS4AAwEAAwIAA20AA7ovAQABHgQ",
                        "AgACAgIAAxkBAAIfIF-7o90tqVHexh6wmIGC6p6B8lriAAIpsDEbx5XZSeCUJv8ce_H5pUUFly4AAwEAAwIAA20AA-dhAwABHgQ",
                        "AgACAgIAAxkBAAIfI1-7o-DCxpdkc5TwtIQcc5eCED7pAAIqsDEbx5XZSTQH1idZ8f8NBPwamC4AAwEAAwIAA20AA4toAwABHgQ"),

                "б" : ("AgACAgIAAxkBAAIfJl-7o-UkaBIpQKdz--QWG0cuY6SjAAIrsDEbx5XZSc937kdmOaSNygefli4AAwEAAwIAA20AA9pPBAABHgQ",
                        "AgACAgIAAxkBAAIfKV-7o-ry5AqpPd9OPtqkWHqX7kZvAAIssDEbx5XZSUfMqH2Fyt1yLQABRZYuAAMBAAMCAANtAAM7uAQAAR4E",
                        "AgACAgIAAxkBAAIfLF-7o-4k1rynKbkAAR9epwABglffHfoAAi6wMRvHldlJ2EQt5ap45NQ1KM2XLgADAQADAgADbQADJkMDAAEeBA",
                        "AgACAgIAAxkBAAIfL1-7o_GLOP3T7YuC5KWA67RbrNhCAAIvsDEbx5XZSW2T-mZ1FTH9ON8UmC4AAwEAAwIAA20AA55tAwABHgQ",
                        "AgACAgIAAxkBAAIfMl-7o_bmmj6B2E8J1WABOluyIfSaAAIwsDEbx5XZSU6VR78AAS8saQ10aJcuAAMBAAMCAANtAAO4egMAAR4E",
                        "AgACAgIAAxkBAAIfNV-7o_oOBbBRKgH5Hnjywhs_RhiIAAIxsDEbx5XZSQvDvwkY938u-9ZWmS4AAwEAAwIAA20AA7M1AQABHgQ"),

                "в" : ("AgACAgIAAxkBAAIfOF-7o_3jeLixoEOg0uG9nb9cGdeyAAIysDEbx5XZSc7c2k-13vVljslTmS4AAwEAAwIAA20AAxMzAQABHgQ",
                        "AgACAgIAAxkBAAIfO1-7pAW5E3WR-NUiZO3KclWwiQowAAIzsDEbx5XZSdWyT_gEtkG9j6Jpli4AAwEAAwIAA20AAx1JBAABHgQ",
                        "AgACAgIAAxkBAAIfPl-7pAjbZRCDBDOhrJP10dTSyHKfAAI0sDEbx5XZSSsBLOFxv_5bcrzRly4AAwEAAwIAA20AA5ZFAwABHgQ",
                        "AgACAgIAAxkBAAIfQV-7pA7Dhep4_z0Sjk2z50wwG8L-AAI1sDEbx5XZSY2xF7YQf63licfxly4AAwEAAwIAA20AA4xYAwABHgQ",
                        "AgACAgIAAxkBAAIgjF-7weHs24th1DDHfPqnlwtNVE4SAAJksDEbx5XZSflMGaMiUr_FdVz4lC4AAwEAAwIAA20AA2WlBgABHgQ",
                        "AgACAgIAAxkBAAIgj1-7weYI3vx6oVtjmXHJWwGbLkvtAAJlsDEbx5XZSR6k1WwnX9KpAcfxly4AAwEAAwIAA20AAy1YAwABHgQ"),

                "г" : ("AgACAgIAAxkBAAIgkl-7weuetlTrocuEcJLRvtIbhFdTAAJmsDEbx5XZSU5QFaRWzAABKlDpPpYuAAMBAAMCAANtAANOuwQAAR4E",
                        "AgACAgIAAxkBAAIglV-7we8uiC1-1BznhGy9fwJ_KWdyAAJnsDEbx5XZSbIGYqkwJbGuwddWmS4AAwEAAwIAA20AA-gxAQABHgQ",
                        "AgACAgIAAxkBAAIgmF-7wfMGmp6kxgEB1F80y82HiO4nAAJosDEbx5XZSaiP37E4Kjtz3WYWmC4AAwEAAwIAA20AA0JsAwABHgQ",
                        "AgACAgIAAxkBAAIgm1-7wfmWhflmtN89qW7PsUx_NihmAAJpsDEbx5XZSdKdFczz3YDwS2_Uli4AAwEAAwIAA20AA5oOBAABHgQ",
                        "AgACAgIAAxkBAAIgnl-7wf4G9tNXRn1P6ZS4UHqRBgzFAAJqsDEbx5XZSZdkIwU9b7l05x9zly4AAwEAAwIAA20AA4R_AwABHgQ",
                        "AgACAgIAAxkBAAIgoV-7wgbbPJu5NRtAtpQYSj3jsDE_AAJrsDEbx5XZSTPjyy8JnJDSx7zRly4AAwEAAwIAA20AA4lAAwABHgQ")},
        "ВЫЧИТАНИЕ" : {
                "а" : ( "AgACAgIAAxkBAAIpBl_AIclHjBEiH0lclhqP5aO5vqTPAAImsDEbXZ8BSvKZotvZ01fxiEHwly4AAwEAAwIAA20AAyuBAwABHgQ",
                        "AgACAgIAAxkBAAIg71-71hMZVcuBla9dnz3299bE0oubAAKrsDEbx5XZSQyjaJ7HhDBULvkamC4AAwEAAwIAA20AA-ttAwABHgQ",
                        "AgACAgIAAxkBAAIg8l-71hkWxATjFysSCFujZxssPI2jAAKssDEbx5XZSUnymDMz6n37fOdRmC4AAwEAAwIAA20AA2ZdAwABHgQ",
                        "AgACAgIAAxkBAAIpCV_AIczvTVocSzh7WE184sINwIciAAInsDEbXZ8BSsItDLjUyIDDFtbXly4AAwEAAwIAA20AA5psAwABHgQ",
                        "AgACAgIAAxkBAAIpDF_AIdO-_Y_OyqBVInp1oM74DFAPAAIosDEbXZ8BSlXNQ7Mqj6Nz3E1VmS4AAwEAAwIAA20AA99gAQABHgQ",
                        "AgACAgIAAxkBAAIpD1_AIdhmxyRi51VhrWpJuGlza1fxAAIpsDEbXZ8BSl4yOictkfOSpwPZli4AAwEAAwIAA20AA-U4BAABHgQ"),

                "б" : ( "AgACAgIAAxkBAAIpEl_AIeAqfeNWkvLqU_5zwKUkz1x-AAIqsDEbXZ8BStlzBmUOKU5pPscOmC4AAwEAAwIAA20AA2eaAwABHgQ",
                        "AgACAgIAAxkBAAIpFV_AIeIMsNEpBvwjxCHAvnNmvxgvAAIrsDEbXZ8BSuQvzzMckkLmjWJQmC4AAwEAAwIAA20AA5yDAwABHgQ",
                        "AgACAgIAAxkBAAIpGF_AIeWYKFAj0VxqQRyY9v1ypTgMAAIssDEbXZ8BSjFT1Yd__nEUQCOlli4AAwEAAwIAA20AAwl1BAABHgQ",
                        "AgACAgIAAxkBAAIhB1-71jmcdL_2bv_M9-1xOb8naCBRAAKysDEbx5XZSZ4ObAh_bPOqKBNwly4AAwEAAwIAA20AA--AAwABHgQ",
                        "AgACAgIAAxkBAAIpG1_AIe3Ayx97vxa5B-ecB8kKdZ6vAAItsDEbXZ8BSk7BZd_Mif0rNRvKly4AAwEAAwIAA20AA9poAwABHgQ",
                        "AgACAgIAAxkBAAIhDV-71kAtGcjsc6YRWsc01eVMGUduAAK0sDEbx5XZSXGvmLH2Z_waZRxLli4AAwEAAwIAA20AA2rABAABHgQ"),

                "в" : ( "AgACAgIAAxkBAAIpIV_AIfuNytXMPQl1gMtq8YDs1u_nAAIvsDEbXZ8BSlRJ6GJbBtupKmUWmC4AAwEAAwIAA20AA82QAwABHgQ",
                        "AgACAgIAAxkBAAIhE1-71khKmcw9CyHWZNzAtKgWnYVHAAK2sDEbx5XZSY3F11s_EQaMFEDwly4AAwEAAwIAA20AA8VgAwABHgQ",
                        "AgACAgIAAxkBAAIhFl-71k0COihREClo2lp8lC6aF3ZAAAK3sDEbx5XZSV7iYuoZ_itSrCOlli4AAwEAAwIAA20AAy1SBAABHgQ",
                        "AgACAgIAAxkBAAIpJF_AIgQDh5DPRDVibzBHiM11fEUmAAIwsDEbXZ8BSkHVAUNnht8sLeg-li4AAwEAAwIAA20AA9rkBAABHgQ",
                        "AgACAgIAAxkBAAIhHF-71lQrRH76BLF0pzOsSLk4OaqcAAK5sDEbx5XZSQAB_YKmfiIOdgABrWyWLgADAQADAgADbQADWkgEAAEeBA",
                        "AgACAgIAAxkBAAIpJ1_AIgmm_9kMOC3Xnp4AAaKjxQfktwACMbAxG12fAUogClHF9AaMHm90aJcuAAMBAAMCAANtAAN7ogMAAR4E"),
                "г" : ( "AgACAgIAAxkBAAIpHl_AIfW1whpkuklF2B9p0kA11McAAy6wMRtdnwFKHk_qjLBD2HyWidqWLgADAQADAgADbQADjS4EAAEeBA",
                        "AgACAgIAAxkBAAIpKl_AI6btZ5fFnft-0TzTflhFD0esAAIzsDEbXZ8BSmY-77k2b_mJS2FQmC4AAwEAAwIAA20AA-GBAwABHgQ",
                        "AgACAgIAAxkBAAIpLV_AI6g3OBgVWBCJ_G-lmysBYwdnAAI0sDEbXZ8BSq5BhkOV48LEYPjVli4AAwEAAwIAA20AA2k2BAABHgQ",
                        "AgACAgIAAxkBAAIpMF_AI6ynQk_HQr8zNAABKIk6pxH7fgACNbAxG12fAUpbsbCMqGnKAsbcYZouAAMBAAMCAANtAAMiXQEAAR4E",
                        "AgACAgIAAxkBAAIpM1_AI64jeRLZTTSkfCS-on4YiPjPAAI2sDEbXZ8BSg_roU-Tc1il8m1TmC4AAwEAAwIAA20AAymEAwABHgQ",
                        "AgACAgIAAxkBAAIpNl_AI7KN41ynUQ8bwcNm_Bpj7fC3AAI3sDEbXZ8BSltAkClPeGYW6m7Uli4AAwEAAwIAA20AA6A3BAABHgQ")},
}
TEST_ANSWERS = {"СЛОЖЕНИЕ":{
                "тст" : ("a"),
                "а" : ( "3/4",
                        "4/5",
                        "3/5",
                        "3/6",
                        "8/9",
                        "5/8"),
                "б" : ( "11/15",
                        "20/42",
                        "23/63",
                        "32/63",
                        "17/15",
                        "37/35"),
                "в" : ( "85/21",
                        "17/4",
                        "214/24",
                        "320/42",
                        "149/18",
                        "41/12"),
                "г" : ( "19/18",
                        "8/6",
                        "5/8",
                        "7/8",
                        "11/9",
                        "7/8")},
            "ВЫЧИТАНИЕ" : {
                "а" : ( "1/4",
                        "2/5",
                        "1/5",
                        "2/5",
                        "6/9",
                        "3/8",),
                "б" : ( "1/15",
                        "8/42",
                        "5/63",
                        "4/63",
                        "7/15",
                        "23/35"),
                "в" : ( "29/21",
                        "5/4",
                        "58/24",
                        "44/42",
                        "49/18",
                        "1/12"),
                "г" : ( "11/18",
                        "2/6",
                        "1/8",
                        "1/8",
                        "5/9",
                        "3/8")},
            "ДЕЛЕНИЕ" : {
                "а" : ( "5/12",
                        "35/22",
                        "20/27",
                        "15/8",
                        "18/35",
                        "12/7"),
                "в" : ( "1/4",
                        "1/1",
                        "1/1",
                        "1/2",
                        "1/1",
                        "2/1"),
                "г" : ( "1/4",
                        "1/1",
                        "28/57",
                        "3/2",
                        "1/1",
                        "8/1",)},
            "УМНОЖЕНИЕ" : {
                "а" : ( "5/12",
                        "35/22",
                        "20/27",
                        "15/8",
                        "18/35",
                        "12/7"),
                "б" : ( "13/4",
                        "6/1",
                        "24/1",
                        "156/1",
                        "7/1",
                        "123/1"),
                "в" : ( "1/4",
                        "1/1",
                        "1/1",
                        "1/2",
                        "1/1",
                        "1/2"),
                "г" : ( "1/4",
                        "1/1",
                        "2/3",
                        "3/2",
                        "1/1",
                        "1/2")},
}
